
// Auto-generated by AutoPilot on 29-07-2023 at 20:34:35

const express = require('express');
const router = express.Router();

//Contra games route
router.get('/contra', (req, res) => {
    const contraGames = ['Contra', 'Super C', 'Contra III: The Alien Wars', 'Contra: Hard Corps'];
    res.json(contraGames);
});

//Export the router to be used in other files
module.exports = router;