
// Auto-generated by AutoPilot on 29-07-2023 at 20:20:20

const express = require('express');
const router = express.Router();

// API route to return the top 5 Playstation games of the year
router.get('/goty', (req,res) => {
    const games = ['God of War', 'Marvels Spider-Man', 'Horizon Zero Dawn', 'Persona 5', 'The Last of Us Part II']
    res.json(games);
});

module.exports = router;