
// Auto-generated by AutoPilot on 29-07-2023 at 20:33:19

const express = require('express');
const router = express.Router();

// Route to return an array of 5 Mario games
router.get('/mario', (req, res) => {
    const marioGames = ["Super Mario Bros.", "Super Mario Bros. 2", "Super Mario Bros. 3", "Super Mario World", "Super Mario 64"];
    res.send(marioGames);
});

module.exports = router;